### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by suchakjani** [psxpaul/gradle-execfork-plugin#12]
Hi

Is there a reason the plugins latest versions are not on maven central.

or maybe i am looking at the wrong places ?

https://mvnrepository.com/artifact/com.github.psxpaul/gradle-execfork-plugin

**Comment by javabrett** [comment]
Latest version is 0.1.8 on Gradle Plugins: https://plugins.gradle.org/plugin/com.github.psxpaul.execfork .

**Comment by psxpaul** [comment]
The reason, honestly, pure laziness on my part 😃I've personally found that pushing to the gradle plugin repo is much easier than pushing to maven central. If there's a strong demand for it though, I can push to both.

**Comment by suchakjani** [comment]
I have just started to use gradle, hence i guess was not aware. I guess having a plugin in gradle plugin repo makes a lot of sense.
Your page  https:/.plugins.gradle.org/plugin/com.github.psxpaul.execfork explains things nicely.
It works as explained and saved me a lot of time. Thanks.

**Comment by suchakjani** [comment]
Closing issue
