### ISSUE TITLE
Specify JDK version/location in JavaExecFork

### ISSUE THREAD

**Issue by ragnor** [psxpaul/gradle-execfork-plugin#13]
Hi,

Is there a way to specific JDK that should be used to run JavaExecFork? I run gradle on JDK 10 but need to start before 'test' some java process that doesn't work on Java 10 and has to be started on 1.8.
I've tried to overwrite some environment variables:
```
    environment 'JAVA_HOME', "c:/Java/jdk1.8.0_171"
    environment 'org.gradle.java.home', "c:/Java/jdk1.8.0_171"
```
but it doesn't work.

**Comment by psxpaul** [comment]
I believe JavaExecFork will use the Java that gradle is configured to use. Have you tried using an ExecFork instead, and using "c:/Java/jdk1.8.0_171/bin/java" as the commandLine?

**Comment by ragnor** [comment]
Thanks, the workaround works as I want. 

Still I think that it'll be a useful feature if in JavaExecFork instead of Jvm.current() a path to java.exe can be provided.
