### ISSUE TITLE
error compiling task: Could not get unknown property 'com' for root project

### ISSUE THREAD

**Issue by mikeycoxon** [psxpaul/gradle-execfork-plugin#23]
I created a task of type: com.github.psxpaul.task.JavaExecFork as per the instructions in the readme, but the compilation fails with the message: "Could not get unknown property 'com' for root project 'xxx' of type org.gradle.api.Project."

I am using gradle 5.3 and its in an external .gradle file which has
`apply plugin: 'com.github.psxpaul.execfork'`
at the top of it. 

Does the task have to be defined in another block? is there any other assumptions that aren't supplied in the readme?

**Comment by psxpaul** [comment]
Are you applying the plugin in the same gradle file that you have the `apply plugin: 'com.github.psxpaul.execfork` line?

There's an example [here](https://github.com/psxpaul/gradle-execfork-plugin/tree/master/sample_projects/apply_from) of something similar to what it sounds like you're describing. Adding another JavaExecFork task in the root build.gradle of that example requires adding the plugin to that gradle file as well with:

```
plugins {
  id 'com.github.psxpaul.execfork' version '0.1.10'
}
```

**Comment by eyalroth** [comment]
Could it be that you wrote the code _not_ in the main build file of the project (`build.gradle`)? If so, it's impossible to import plugin classes from external script files.

You can do something like this to overcome this restriction:

```gradle
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath group: 'gradle.plugin.com.github.psxpaul', name: 'gradle-execfork-plugin', version: '0.1.13'
    }
}
// works now
import com.github.psxpaul.task.JavaExecFork
```

See https://discuss.gradle.org/t/cant-access-classes-from-plugin-directly-in-included-script/14721
