### ISSUE TITLE
Incompatible with Gradle 5.6

### ISSUE THREAD

**Issue by DreierF** [psxpaul/gradle-execfork-plugin#26]
Just tested against Gradle 5.6 and since `JavaForkOptions` got two new methods that are not yet implemented by the JavaExecFork task.

The plugin just needs to be recompiled against Gradle 5.6 to automatically inherit the methods from `DefaultJavaForkOptions`.

**Comment by alesbukovsky** [comment]
Please merge the PR and release when possible. This breaks our builds after 5.6 upgrade.
