### ISSUE TITLE
add a waitForOutput option

### ISSUE THREAD

**Issue by mohamnag** [psxpaul/gradle-execfork-plugin#3]
I just wanted to track and eventually be informed of the implementation of this option as this is very critical for my use case. Thanks in advance for providing feedback.

**Comment by ja-ko** [comment]
FYI:
I have implemented waitForOutput in #5 and I'm waiting for the plugin maintainer @psxpaul to review, merge and publish the changes.

**Comment by mohamnag** [comment]
thanks for the heads up!

**Comment by psxpaul** [comment]
This should now be implemented in 0.1.6. Thanks @ja-ko for your PR!
