### ISSUE TITLE
Incompatible with Gradle configuration cache

### ISSUE THREAD

**Issue by abendt** [psxpaul/gradle-execfork-plugin#45]
The plugin cannot be used in a project that also uses the new configuration cache (https://docs.gradle.org/7.2/userguide/configuration_cache.html)

When trying to enable the config cache there is a build failure and this message:

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

```
- Plugin 'com.github.psxpaul.execfork': registration of listener on 'Gradle.addBuildListener' is unsupported
  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners
```

**Comment by britter** [comment]
@psxpaul would be great to have a release containing this fix. Any ETA on that?
