### ISSUE TITLE
JavaExecFork can't be declared outside the main 'build.gradle' script

### ISSUE THREAD

**Issue by enadim** [psxpaul/gradle-execfork-plugin#6]
When the JavaExecFork  task is outside the build.gradle script the following error is thrown: 
> JavaExecFork_Decorated task mytask did not have a joinTask associated

gradle version : 4.3

build.gradle
> apply plugin: 'com.github.psxpaul.execfork'
apply from: 'gradle/exec.gradle'

exec.gradle
>buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies { classpath 'gradle.plugin.com.github.psxpaul:gradle-execfork-plugin:0.1.5' }
}
task mytask(type: com.github.psxpaul.task.JavaExecFork) {
    main = 'MayApplication'
    classpath = sourceSets.test.runtimeClasspath
    workingDir = "$buildDir"
    standardOutput = "$buildDir/application.log"
    errorOutput = "$buildDir/application-error.log"
    waitForPort = 7777
    timeout = 30
}

**Comment by psxpaul** [comment]
The sample projects all have:
> apply plugin: 'gradle-execfork-plugin'

instead of the apply statement that you have. Does that make any differences in your case? If not, I'll try to take a look at this later this week.

**Comment by psxpaul** [comment]
Actually, it looks like this is a limitation of gradle. When applying from another *.gradle file, you can't apply other plugins. The workaround is to apply the class of the plugin, rather than the name. See:

http://mrhaki.blogspot.com/2015/10/gradle-goodness-apply-external-script.html
https://discuss.gradle.org/t/how-do-i-apply-a-plugin-to-a-project-from-a-shared-applied-gradle-file/7508

I'll add a sample project to the source, to make sure this doesn't break.

**Comment by enadim** [comment]
The plugin has not been published to maven central.

the test [project](https://github.com/psxpaul/gradle-execfork-plugin/blob/master/sample_projects/apply_from/gradle/exec.gradle) doesn't work due to mavenLocal() 
```gradle
buildscript {
  repositories {
    mavenLocal() 
    mavenCentral()
  }
  dependencies {
    classpath "com.github.psxpaul:gradle-execfork-plugin:$pluginVersion"
  }
}
apply plugin: com.github.psxpaul.ExecForkPlugin
```

Here is the code snippet that works fine:
```gradle
buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.psxpaul:gradle-execfork-plugin:0.1.6"
    }
}
apply plugin: com.github.psxpaul.ExecForkPlugin
```

Thanks Paul for closing this issue, it really helps (I had too many exec that I can split now).
