### ISSUE TITLE
Can't set system properties

### ISSUE THREAD

**Issue by flooose** [psxpaul/gradle-execfork-plugin#8]
Hi, I'm trying to set system properties in a task that uses your plugin. In other parts of my `build.gradle`, I can call the `systemProperty` method as follows:

```
bootRun {
  systemProperty 'spring.profiles.active', 'dev'
}
```
and then the properties from my `application-dev.properties` are loaded. When I try to call this method in a task with `type: com.github.psxpaul.task.JavaExecFork`, I get the error:

```
Could not find method systemProperty() for arguments [spring.profiles.active, dev] on task ':protractorServer' of type com.github.psxpaul.task.JavaExecFork.
```
Is there a way to  set this property, or am I missing something?

**Comment by javabrett** [comment]
Can you update the issue, adding the task block?

**Comment by natasha4** [comment]
I have the same issue. For `JavaExec` we can pass system properties like this:
```
task task1(type: JavaExec) {
    main = "cucumber.api.cli.Main"
    classpath = sourceSets.test.output
    systemProperties = System.properties
}
```
But I can't do the same for `JavaExecFork` unfortunately:
```
task task2(type: JavaExecFork) {
    classpath = sourceSets.test.output
    main = 'com.test.Test'
    systemProperties = System.properties << exception! 
}
```
 It would be great if `JavaExecFork` supports `systemProperties`
